### ISSUE TITLE
Could not resolve all dependencies.

### ISSUE THREAD

**Issue by KenwoodFox** [bartoszek/AUR-meshroom#6]
Getting this error trying to build on manjaro/arch
```pamac build meshroom                                                                                                                                 ─╯
Preparing...
Cloning meshroom build files...
Checking meshroom dependencies...
Cloning alice-vision build files...
Checking alice-vision dependencies...
Resolving dependencies...
Checking inter-conflicts...

To build (2):
  alice-vision  2.3.1-2       AUR
  meshroom      2020.1.1-2    AUR


Edit build files : [e] 
Apply transaction ? [e/y/N] y


Building alice-vision...
==> Making package: alice-vision 2.3.1-2 (Fri 19 Feb 2021 02:07:10 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> popsift
  -> uncertainty-framework
  -> magma
==> ERROR: Could not resolve all dependencies.
```
am i missing something? Thanks so much for reading this.

**Comment by ChemicalXandco** [comment]
Run `[your AUR helper] --needed -S popsift uncertainty-framework cuda` to get the optional dependencies.

Alternatively you can disable them by setting the following environment variables:
```
DISABLE_CUDA=1
DISABLE_POPSIFT=1
DISABLE_UTE=1
```

**Comment by KenwoodFox** [comment]
Thanks for the suggestion, i dont think it worked though 
![image](https://user-images.githubusercontent.com/31870999/108543121-a56c1080-72b2-11eb-8865-0e412182fdb6.png)
I dont want to not use cuda, my GPU can do that.

**Comment by KenwoodFox** [comment]
Sorry for the silly questions, im a bit new to GNU based UNIX distros

**Comment by ChemicalXandco** [comment]
`pacman` only searches the main repositories, you should use a AUR helper like `yay` for example. If you do not need CUDA you do not need the optional dependencies. Run `export DISABLE_CUDA=1 DISABLE_POPSIFT=1 DISABLE_UTE=1` before build to disable CUDA.

**Comment by KenwoodFox** [comment]
Thanks so much for the help, i tried using yay, heres my results
![image](https://user-images.githubusercontent.com/31870999/108550248-4dd2a280-72bc-11eb-8ac0-85725cd755f7.png)

**Comment by ChemicalXandco** [comment]
[This still needs to be resolved](https://bugs.archlinux.org/task/69629) and I cannot remember exactly how I got around this issue but I think it involved reinstalling some packages.

**Comment by KenwoodFox** [comment]
Oh no, is it an issue on my end then or something else? Is there anything I can do to help?

**Comment by ChemicalXandco** [comment]
It has been fixed in `cuda 11.2.1-2`, the next stable manjaro update should include this but you can always change to unstable/testing if you need the fix sooner.

**Comment by KenwoodFox** [comment]
That sounds great! Sorry for asking here but, when does the next manjaro update come out, and how would I switch to unstable/testing if I wanted a quicker fix?

**Comment by bartoszek** [comment]
@KenwoodFox : Sorry, I'm late to the party 😏 

To quickly pull `testing` package to your system: `pacman -U` supports URL, just find repo mirror on https://repo.manjaro.org/ got through repo structure to package file, and copy package url:
This should work:
```
pacman -U http://mirror.easyname.at/manjaro/testing/community/x86_64/cuda-11.2.1-2-x86_64.pkg.tar.zst
```

More automatic solution you can temporary switch mirrors to `testing` branch to install required package.
```bash
sudo pacman-mirrors -aS testing
sudo pacman -Syyu cuda
sudo pacman-mirrors -aS stable && sudo pacman -Syy
```

As for _how long one have to wait for packages to land in `stable` repository_ it's usually about 2 weeks for package to get from `testing` to `stable`, and about 2-3 days for package to get from `unstable` to `testing` https://wiki.manjaro.org/index.php/Switching_Branches

@ChemicalXandco : To explain myself here, `popsift` was intended to be used with `cuda-spilt` package (https://github.com/bartoszek/AUR-cuda-split) , but I've removed it from AUR since `community/cuda` adopt split package.

**Comment by bartoszek** [comment]
@KenwoodFox @ChemicalXandco I must warn you lads, latest `cuda` package is still broken -  preventing successful lock of `libcudart` in `popsift-libs`. Until [task #69829](https://bugs.archlinux.org/task/69829) gets resolved. I'll remove `libcudart.so` temporarily to override lib lock :feelsgood:

**Comment by bartoszek** [comment]
@KenwoodFox @ChemicalXandco [#69829](https://bugs.archlinux.org/task/69829) was fixed, I'd rolled back last changes and close the issue - feel free to reopen if problem reoccur.
